--
-- PostgreSQL database dump
--

\restrict cCLSGDqPYkIKBV5P5lucRWZ8JulPk1XgFqNwxye7PUvP4zQ64rlRF1QZKbrK3jB

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tb_client; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_client (
    id bigint NOT NULL,
    active boolean NOT NULL,
    person_id bigint NOT NULL
);


ALTER TABLE public.tb_client OWNER TO postgres_user_admin;

--
-- Name: tb_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE public.tb_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_person; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_person (
    id bigint NOT NULL,
    active boolean NOT NULL,
    bairro character varying(255),
    cep character varying(8),
    cidade character varying(255),
    complemento character varying(255),
    cpf_cnpj character varying(14) NOT NULL,
    email character varying(255) NOT NULL,
    logradouro character varying(255),
    name character varying(255) NOT NULL,
    nome_fantasia character varying(255),
    numero character varying(255),
    phone character varying(11),
    rg_ie character varying(20),
    tipo_pessoa character varying(2) NOT NULL,
    uf character varying(2)
);


ALTER TABLE public.tb_person OWNER TO postgres_user_admin;

--
-- Name: tb_person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE public.tb_person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_refresh_tokens; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_refresh_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    jti character varying(255) NOT NULL,
    revoked boolean NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.tb_refresh_tokens OWNER TO postgres_user_admin;

--
-- Name: tb_refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE public.tb_refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_supplier; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_supplier (
    id bigint NOT NULL,
    active boolean NOT NULL,
    agencia character varying(255),
    banco character varying(255),
    chave_pix character varying(255),
    conta character varying(255),
    tipo_conta character varying(255),
    categoria character varying(255),
    condicao_pagamento_padrao character varying(255),
    observacoes_comerciais text,
    prazo_entrega_dias integer,
    valor_minimo_pedido numeric(38,2),
    person_id bigint NOT NULL
);


ALTER TABLE public.tb_supplier OWNER TO postgres_user_admin;

--
-- Name: tb_supplier_contacts; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_supplier_contacts (
    supplier_id bigint NOT NULL,
    cargo character varying(255),
    email character varying(255),
    nome character varying(255),
    setor character varying(255),
    telefone character varying(255)
);


ALTER TABLE public.tb_supplier_contacts OWNER TO postgres_user_admin;

--
-- Name: tb_supplier_documents; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_supplier_documents (
    supplier_id bigint NOT NULL,
    data_validade date,
    numero_ou_url character varying(255),
    tipo_documento character varying(255)
);


ALTER TABLE public.tb_supplier_documents OWNER TO postgres_user_admin;

--
-- Name: tb_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE public.tb_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_users; Type: TABLE; Schema: public; Owner: postgres_user_admin
--

CREATE TABLE public.tb_users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(50) NOT NULL
);


ALTER TABLE public.tb_users OWNER TO postgres_user_admin;

--
-- Name: tb_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE public.tb_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: tb_client; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_client (id, active, person_id) FROM stdin;
1	t	1
\.


--
-- Data for Name: tb_person; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_person (id, active, bairro, cep, cidade, complemento, cpf_cnpj, email, logradouro, name, nome_fantasia, numero, phone, rg_ie, tipo_pessoa, uf) FROM stdin;
1	t	Setor São José	74440150	Goiânia	\N	85717475713	lavinia_olivia_pereira@msn.com	Rua I	Lavínia Olivia Pereira	\N	466	62997023691	289971032	PF	GO
2	t	Chácaras Alvorada	18215400	Itapetininga		24435853000114	compras@emanuelelaiscontabilltda.com.br	Rua Eugenia Ayres da Silva Leite	Emanuel e Laís Contábil Ltda		449	1539237218	587733630100	PJ	SP
\.


--
-- Data for Name: tb_refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_refresh_tokens (id, expiry_date, jti, revoked, username) FROM stdin;
1	2026-09-22 13:28:55.116684+00	6f02ff76-d2f5-44c7-99a5-a22badd6b0cd	f	admin
2	2026-09-22 13:37:58.388927+00	92a5b843-64d6-419a-843c-82ca370cc328	f	admin
3	2026-09-22 13:39:22.949519+00	8231bd84-047a-4c0f-b6b1-8b3453d675bb	f	admin
4	2026-09-22 13:54:04.340994+00	fce26885-a88e-4467-8a2c-931225730f46	f	admin
5	2026-09-23 20:49:14.998108+00	ea769e34-8bbd-4fba-a22e-120aaa9a7b99	f	admin
6	2026-09-24 01:04:49.531909+00	52558bde-847c-4f8b-b67b-22729f7cfdd1	f	admin
7	2026-09-24 01:20:27.113932+00	f1487fd2-5a78-4263-8792-eb0a68ea0ed3	f	admin
8	2026-09-24 10:56:26.527799+00	f30ceaac-2547-4efe-9376-ce5be507459c	f	admin
9	2026-09-24 11:14:03.436882+00	d05a3509-b5f2-4cdb-92c7-3997fc99f1d0	f	admin
10	2026-09-24 11:29:30.923811+00	59dd6d23-bad8-40c3-a369-b71ec6661f53	f	admin
11	2026-09-24 11:52:31.319623+00	c40f19d8-c189-46f9-8cf9-c7a4743622e2	f	admin
12	2026-09-24 11:58:48.885559+00	dd5051eb-31d1-43a3-ba0b-4a689ce3543e	f	admin
\.


--
-- Data for Name: tb_supplier; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_supplier (id, active, agencia, banco, chave_pix, conta, tipo_conta, categoria, condicao_pagamento_padrao, observacoes_comerciais, prazo_entrega_dias, valor_minimo_pedido, person_id) FROM stdin;
1	t	2255	237 - Bradesco	\N	1211649-7	CORRENTE	Serviços	15 DIAS		15	200.00	2
\.


--
-- Data for Name: tb_supplier_contacts; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_supplier_contacts (supplier_id, cargo, email, nome, setor, telefone) FROM stdin;
1	Vendedora	raimunda_daconceicao@sadefem.com.br	Raimunda Isabelle Carla da Conceição	Comercial	(79) 3576-9254
\.


--
-- Data for Name: tb_supplier_documents; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_supplier_documents (supplier_id, data_validade, numero_ou_url, tipo_documento) FROM stdin;
\.


--
-- Data for Name: tb_users; Type: TABLE DATA; Schema: public; Owner: postgres_user_admin
--

COPY public.tb_users (id, active, email, name, password, role, username) FROM stdin;
1	t	admin@lexdev.net.br	Administrator	$2a$10$srGQNB7fduO91S6pFiL7.umDXXWDbZHDYdq1HrSovQvCMX7wjBq8W	ROLE_ADMIN	admin
\.


--
-- Name: tb_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres_user_admin
--

SELECT pg_catalog.setval('public.tb_client_id_seq', 1, true);


--
-- Name: tb_person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres_user_admin
--

SELECT pg_catalog.setval('public.tb_person_id_seq', 2, true);


--
-- Name: tb_refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres_user_admin
--

SELECT pg_catalog.setval('public.tb_refresh_tokens_id_seq', 12, true);


--
-- Name: tb_supplier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres_user_admin
--

SELECT pg_catalog.setval('public.tb_supplier_id_seq', 1, true);


--
-- Name: tb_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres_user_admin
--

SELECT pg_catalog.setval('public.tb_users_id_seq', 1, true);


--
-- Name: tb_client tb_client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_client
    ADD CONSTRAINT tb_client_pkey PRIMARY KEY (id);


--
-- Name: tb_person tb_person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_person
    ADD CONSTRAINT tb_person_pkey PRIMARY KEY (id);


--
-- Name: tb_refresh_tokens tb_refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_refresh_tokens
    ADD CONSTRAINT tb_refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: tb_supplier tb_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_supplier
    ADD CONSTRAINT tb_supplier_pkey PRIMARY KEY (id);


--
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (id);


--
-- Name: tb_users uk8n82lwp7lflhwda2v2v3wckc9; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT uk8n82lwp7lflhwda2v2v3wckc9 UNIQUE (username);


--
-- Name: tb_supplier ukc26wr4jwyr4fcx1m318hr0fgx; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_supplier
    ADD CONSTRAINT ukc26wr4jwyr4fcx1m318hr0fgx UNIQUE (person_id);


--
-- Name: tb_users ukgrd22228p1miaivbn9yg178pm; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT ukgrd22228p1miaivbn9yg178pm UNIQUE (email);


--
-- Name: tb_person ukhhhpn6bi8cg4m7jscavckytxh; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_person
    ADD CONSTRAINT ukhhhpn6bi8cg4m7jscavckytxh UNIQUE (cpf_cnpj);


--
-- Name: tb_refresh_tokens ukmei0a8xykyp7n7bbmp97mx37a; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_refresh_tokens
    ADD CONSTRAINT ukmei0a8xykyp7n7bbmp97mx37a UNIQUE (jti);


--
-- Name: tb_client ukne6nv2jshagun6yo2t7j7532; Type: CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_client
    ADD CONSTRAINT ukne6nv2jshagun6yo2t7j7532 UNIQUE (person_id);


--
-- Name: tb_supplier_contacts fkce2b5s7hvfqgncfpb93kuhdj8; Type: FK CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_supplier_contacts
    ADD CONSTRAINT fkce2b5s7hvfqgncfpb93kuhdj8 FOREIGN KEY (supplier_id) REFERENCES public.tb_supplier(id);


--
-- Name: tb_client fkf22nvspbbr3gny3pokxrtq02h; Type: FK CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_client
    ADD CONSTRAINT fkf22nvspbbr3gny3pokxrtq02h FOREIGN KEY (person_id) REFERENCES public.tb_person(id);


--
-- Name: tb_supplier fkju9srdvxprdm9cp19nr3cfwrv; Type: FK CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_supplier
    ADD CONSTRAINT fkju9srdvxprdm9cp19nr3cfwrv FOREIGN KEY (person_id) REFERENCES public.tb_person(id);


--
-- Name: tb_supplier_documents fkrav068tmn3wqqet0vdigv5caa; Type: FK CONSTRAINT; Schema: public; Owner: postgres_user_admin
--

ALTER TABLE ONLY public.tb_supplier_documents
    ADD CONSTRAINT fkrav068tmn3wqqet0vdigv5caa FOREIGN KEY (supplier_id) REFERENCES public.tb_supplier(id);


--
-- PostgreSQL database dump complete
--

\unrestrict cCLSGDqPYkIKBV5P5lucRWZ8JulPk1XgFqNwxye7PUvP4zQ64rlRF1QZKbrK3jB

