BEGIN;

UPDATE tb_supplier_documents
SET tipo_documento = 'OUTRO'
WHERE tipo_documento IS NULL
   OR btrim(tipo_documento) = '';

-- A tabela antiga era ElementCollection e não possuía chave própria.
-- Criamos a identidade explicitamente e preenchemos também os registros existentes.
CREATE SEQUENCE tb_supplier_documents_id_seq;

ALTER TABLE tb_supplier_documents
    ADD COLUMN id BIGINT;

UPDATE tb_supplier_documents
SET id = nextval('tb_supplier_documents_id_seq');

SELECT setval(
    'tb_supplier_documents_id_seq',
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM tb_supplier_documents;

ALTER TABLE tb_supplier_documents
    ALTER COLUMN id SET DEFAULT nextval('tb_supplier_documents_id_seq'),
    ALTER COLUMN id SET NOT NULL;

ALTER SEQUENCE tb_supplier_documents_id_seq
    OWNED BY tb_supplier_documents.id;

ALTER TABLE tb_supplier_documents
    ADD CONSTRAINT tb_supplier_documents_pkey PRIMARY KEY (id);

ALTER TABLE tb_supplier_documents
    ALTER COLUMN tipo_documento SET NOT NULL;

ALTER TABLE tb_supplier_documents
    ADD COLUMN data_emissao DATE,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX idx_supplier_documents_supplier_active
    ON tb_supplier_documents (supplier_id, active);

CREATE INDEX idx_supplier_documents_tipo
    ON tb_supplier_documents (supplier_id, tipo_documento);

CREATE TABLE tb_supplier_document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    scan_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,

    CONSTRAINT fk_supplier_document_versions_document
        FOREIGN KEY (document_id)
        REFERENCES tb_supplier_documents(id),

    CONSTRAINT fk_supplier_document_versions_user
        FOREIGN KEY (created_by)
        REFERENCES tb_users(id),

    CONSTRAINT uk_supplier_document_versions_number
        UNIQUE (document_id, version_number),

    CONSTRAINT uk_supplier_document_versions_storage_key
        UNIQUE (storage_key),

    CONSTRAINT ck_supplier_document_versions_scan_status
        CHECK (scan_status IN ('CLEAN', 'QUARANTINED'))
);

CREATE INDEX idx_supplier_document_versions_document
    ON tb_supplier_document_versions (document_id, version_number DESC);

CREATE INDEX idx_supplier_document_versions_scan_status
    ON tb_supplier_document_versions (scan_status);

COMMIT;