-- ============================================================
-- V1 - Schema inicial do SystemPro
--
-- Fonte:
-- Backup do banco realizado antes da adoção do Flyway.
--
-- Esta migration representa exatamente o schema existente
-- antes da V2.
--
-- Não contém:
--   - flyway_schema_history
--   - dados do banco
--   - estruturas introduzidas posteriormente pela V4
--   - campos de auditoria/version da V2
-- ============================================================



-- ============================================================
-- TB_PERSON
-- ============================================================

CREATE TABLE public.tb_person (
    id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,

    bairro VARCHAR(255),
    cep VARCHAR(8),
    cidade VARCHAR(255),
    complemento VARCHAR(255),
    cpf_cnpj VARCHAR(14) NOT NULL,
    email VARCHAR(255) NOT NULL,
    logradouro VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),
    numero VARCHAR(255),
    phone VARCHAR(11),
    rg_ie VARCHAR(20),
    tipo_pessoa VARCHAR(2) NOT NULL,
    uf VARCHAR(2),

    CONSTRAINT tb_person_pkey
        PRIMARY KEY (id),

    CONSTRAINT ukhhhpn6bi8cg4m7jscavckytxh
        UNIQUE (cpf_cnpj)
);


ALTER TABLE public.tb_person
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.tb_person_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );



-- ============================================================
-- TB_CLIENT
-- ============================================================

CREATE TABLE public.tb_client (
    id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    person_id BIGINT NOT NULL,

    CONSTRAINT tb_client_pkey
        PRIMARY KEY (id),

    CONSTRAINT ukne6nv2jshagun6yo2t7j7532
        UNIQUE (person_id),

    CONSTRAINT fkf22nvspbbr3gny3pokxrtq02h
        FOREIGN KEY (person_id)
        REFERENCES public.tb_person (id)
);


ALTER TABLE public.tb_client
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.tb_client_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- ============================================================
-- TB_REFRESH_TOKENS
-- ============================================================

CREATE TABLE public.tb_refresh_tokens (
    id BIGINT NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    jti VARCHAR(255) NOT NULL,
    revoked BOOLEAN NOT NULL,
    username VARCHAR(255) NOT NULL,

    CONSTRAINT tb_refresh_tokens_pkey
        PRIMARY KEY (id),

    CONSTRAINT ukmei0a8xykyp7n7bbmp97mx37a
        UNIQUE (jti)
);


ALTER TABLE public.tb_refresh_tokens
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.tb_refresh_tokens_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


-- ============================================================
-- TB_SUPPLIER
-- ============================================================

CREATE TABLE public.tb_supplier (
    id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,

    agencia VARCHAR(255),
    banco VARCHAR(255),
    chave_pix VARCHAR(255),
    conta VARCHAR(255),
    tipo_conta VARCHAR(255),
    categoria VARCHAR(255),
    condicao_pagamento_padrao VARCHAR(255),
    observacoes_comerciais TEXT,
    prazo_entrega_dias INTEGER,
    valor_minimo_pedido NUMERIC(38,2),

    person_id BIGINT NOT NULL,

    CONSTRAINT tb_supplier_pkey
        PRIMARY KEY (id),

    CONSTRAINT ukc26wr4jwyr4fcx1m318hr0fgx
        UNIQUE (person_id),

    CONSTRAINT fkju9srdvxprdm9cp19nr3cfwrv
        FOREIGN KEY (person_id)
        REFERENCES public.tb_person (id)
);


ALTER TABLE public.tb_supplier
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.tb_supplier_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


-- ============================================================
-- TB_SUPPLIER_CONTACTS
-- ============================================================

CREATE TABLE public.tb_supplier_contacts (
    supplier_id BIGINT NOT NULL,
    cargo VARCHAR(255),
    email VARCHAR(255),
    nome VARCHAR(255),
    setor VARCHAR(255),
    telefone VARCHAR(255),

    CONSTRAINT fkce2b5s7hvfqgncfpb93kuhdj8
        FOREIGN KEY (supplier_id)
        REFERENCES public.tb_supplier (id)
);


-- ============================================================
-- TB_SUPPLIER_DOCUMENTS
-- ============================================================

CREATE TABLE public.tb_supplier_documents (
    supplier_id BIGINT NOT NULL,
    data_validade DATE,
    numero_ou_url VARCHAR(255),
    tipo_documento VARCHAR(255),

    CONSTRAINT fkrav068tmn3wqqet0vdigv5caa
        FOREIGN KEY (supplier_id)
        REFERENCES public.tb_supplier (id)
);


-- ============================================================
-- TB_USERS
-- ============================================================

CREATE TABLE public.tb_users (
    id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL,

    CONSTRAINT tb_users_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk8n82lwp7lflhwda2v2v3wckc9
        UNIQUE (username),

    CONSTRAINT ukgrd22228p1miaivbn9yg178pm
        UNIQUE (email)
);


ALTER TABLE public.tb_users
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.tb_users_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );