-- ============================================================
-- V4 - Criar nova estrutura de Person
-- ============================================================

-- ------------------------------------------------------------
-- Dados específicos de Pessoa Física
-- ------------------------------------------------------------
CREATE TABLE public.tb_individual_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT NOT NULL,
    rg VARCHAR(20),

    CONSTRAINT tb_individual_person_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_individual_person_person
        UNIQUE (person_id),

    CONSTRAINT fk_individual_person_person
        FOREIGN KEY (person_id)
        REFERENCES public.tb_person (id)
);

-- ------------------------------------------------------------
-- Dados específicos de Pessoa Jurídica
-- ------------------------------------------------------------
CREATE TABLE public.tb_legal_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT NOT NULL,
    nome_fantasia VARCHAR(150),
    inscricao_estadual VARCHAR(20),

    CONSTRAINT tb_legal_entity_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_legal_entity_person
        UNIQUE (person_id),

    CONSTRAINT fk_legal_entity_person
        FOREIGN KEY (person_id)
        REFERENCES public.tb_person (id)
);

-- ------------------------------------------------------------
-- Contatos da pessoa
-- ------------------------------------------------------------
CREATE TABLE public.tb_person_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    value VARCHAR(255) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(150),

    CONSTRAINT tb_person_contact_pkey
        PRIMARY KEY (id),

    CONSTRAINT fk_person_contact_person
        FOREIGN KEY (person_id)
        REFERENCES public.tb_person (id)
);

CREATE INDEX idx_person_contact_person
    ON public.tb_person_contact (person_id);

-- ------------------------------------------------------------
-- Endereços da pessoa
-- ------------------------------------------------------------
CREATE TABLE public.tb_person_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    cep VARCHAR(8),
    logradouro VARCHAR(150),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf VARCHAR(2),
    principal BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT tb_person_address_pkey
        PRIMARY KEY (id),

    CONSTRAINT fk_person_address_person
        FOREIGN KEY (person_id)
        REFERENCES public.tb_person (id)
);

CREATE INDEX idx_person_address_person
    ON public.tb_person_address (person_id);