# Nome da Aplicação
spring.application.name=systempro-api

# Configuração de Conexão com o PostgreSQL
# Utiliza a sintaxe ${VARIAVEL:valor_padrao} para funcionar tanto no Docker quanto rodando direto no Spring Boot/IDE
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lexdevdb}
spring.datasource.username=${DB_USER:postgres_user_admin}
spring.datasource.password=${DB_PASSWORD:Password@dmin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
# 'update' atualiza a estrutura do banco automaticamente a partir das suas entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações de Segurança e JWT (Variáveis customizadas)
jwt.secret=${SECRET_KEY:defaultSecretKeyForLocalDevelopmentOnlyMustBeLongEnough12345}
jwt.issuer=${JWT_ISSUER:https://lexdev.ddns.net}
jwt.audience=${JWT_AUDIENCE:sistema-api}

# Configura o Swagger UI para buscar os schemas com o prefixo do Nginx (/api)
springdoc.swagger-ui.url=/api/v3/api-docs
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config

# Faz o Spring reconhecer o X-Forwarded-Prefix enviado pelo Nginx (/api)
server.forward-headers-strategy=framework

# Ativa logs detalhados do Spring Security e do Web Dispatcher
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

